// Generated by CoffeeScript 1.6.2
(function() {
  var cheerio, core, exports;

  core = require('./core');

  cheerio = require('cheerio');

  exports = module.exports = {
    data: [
      {
        S1: 56,
        subtype: 60,
        sizecode: 60
      }, {
        S1: 56,
        subtype: 90,
        sizecode: 90
      }, {
        S1: 56,
        subtype: 120,
        sizecode: 120
      }, {
        S1: 56,
        subtype: 130,
        sizecode: 130
      }, {
        S1: 56,
        subtype: 140,
        sizecode: 140
      }, {
        S1: 56,
        subtype: 150,
        sizecode: 150
      }, {
        S1: 55,
        subtype: 30,
        sizecode: 30
      }, {
        S1: 55,
        subtype: 35,
        sizecode: 35
      }, {
        S1: 55,
        subtype: 40,
        sizecode: 40
      }, {
        S1: 55,
        subtype: 50,
        sizecode: 50
      }, {
        S1: 55,
        subtype: 60,
        sizecode: 60
      }, {
        S1: 57,
        subtype: 18,
        sizecode: 18
      }, {
        S1: 57,
        subtype: 20,
        sizecode: 20
      }, {
        S1: 57,
        subtype: 23,
        sizecode: 23
      }, {
        S1: 57,
        subtype: 25,
        sizecode: 25
      }, {
        S1: 57,
        subtype: 30,
        sizecode: 30
      }, {
        S1: 57,
        subtype: 35,
        sizecode: 35
      }, {
        S1: 57,
        subtype: 40,
        sizecode: 40
      }, {
        S1: 54,
        subtype: 30,
        sizecode: 30
      }, {
        S1: 54,
        subtype: 40,
        sizecode: 40
      }
    ],
    rootURL: '/purchasing/compare/fan.asp',
    init: function(options) {
      if (options == null) {
        options = {
          source: 'file'
        };
      }
      return this.getHTTPFromArray({
        url: core.baseURL + this.rootURL,
        body: this.data[9]
      }, function(result) {
        return console.log('result = ', result);
      });
    },
    getHTTPFromArray: function(options, cb) {
      var _this = this;

      if (options == null) {
        options = {
          url: core.baseURL + this.rootURL,
          body: ''
        };
      }
      return core.getHtmlForm({
        url: options.url,
        body: options.body
      }, function($) {
        return _this.getFormHtml($, function(result) {
          return cb(result);
        });
      });
    },
    getFileFromArray: function(options, cb) {
      var _this = this;

      if (options == null) {
        options = {
          path: './data/1371999790466_fan.html'
        };
      }
      return core.getFileHtml(options.path, function($) {
        return _this.getFormHtml($, function(result) {
          return cb(result);
        });
      });
    },
    getFormHtml: function($, cb) {
      return $('form').each(function(index, item) {
        var header, result;

        if ($(item).attr('action').indexOf('/purchasing/compare/fan.asp?') >= 0) {
          header = [];
          result = [];
          return $(item).find('table').each(function(index, item) {
            var tmp, _index;

            _index = index;
            tmp = {};
            $(item).find('td').each(function(index, item) {
              var h;

              if (_index === 0) {
                return header.push($(item).text());
              } else {
                if (index % header.length === 0 && index !== 0) {
                  result.push(tmp);
                  tmp = {};
                }
                h = header[index % header.length];
                return tmp[h] = $(item).text();
              }
            });
            return cb(result);
          });
        }
      });
    }
  };

}).call(this);
